const module1 = require('./module1')
const module2 = require('./module2')
const module3 = require('./module3')
console.log(module1.username)
console.log(module2.username)
console.log(module3.username)
