const ADD_TODO = 'ADD_TODO'
const UPDATE_TODO = 'UPDATE_TODO'
const DELETE_TODO = 'DELETE_TODO'
const ALL_CHECKED = 'All_CHECKED'
const DELETE_ALL_DONE = 'DELETE_ALL_DONE'
export { ADD_TODO, UPDATE_TODO, DELETE_TODO, ALL_CHECKED, DELETE_ALL_DONE }
